# -*- coding: utf-8 -*-
"""Seq2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SsakJnV56hgDtj4cEWAb9MBbW4P1yruV
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.models import Sequential

train=pd.read_csv("engtamilTrain.csv", engine='python', on_bad_lines='warn')
train=train.drop(["Unnamed: 0"],axis=1)
english_sentences=train["en"]
tamil_sentence=train['ta']
english_sentences=english_sentences.head(1000)
tamil_sentences=tamil_sentence.head(1000)

"""| **Code**                                                                         | **Description**                                                                                                                                      |
| -------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------- |
| `import pandas as pd`                                                            | Imports the **Pandas** library for reading and manipulating datasets.                                                                                |
| `import numpy as np`                                                             | Imports the **NumPy** library for numerical operations and arrays.                                                                                   |
| `import tensorflow as tf`                                                        | Imports the **TensorFlow** deep learning framework.                                                                                                  |
| `from tensorflow import keras`                                                   | Imports the **Keras** API from TensorFlow to build neural networks.                                                                                  |
| `from tensorflow.keras.layers import Embedding, LSTM, Dense`                     | Imports the required neural network layers: **Embedding** (word vectors), **LSTM** (sequence learning), and **Dense** (output layer).                |
| `from tensorflow.keras.models import Sequential`                                 | Imports the **Sequential** model to build the neural network layer by layer.                                                                         |
| `train = pd.read_csv("engtamilTrain.csv", engine='python', on_bad_lines='warn')` | Reads the **English–Tamil training dataset** from the CSV file. If a row has formatting issues, it displays a warning instead of stopping execution. |
| `train = train.drop(["Unnamed: 0"], axis=1)`                                     | Removes the unnecessary **Unnamed: 0** column, which is usually an index column created during CSV export.                                           |
| `english_sentences = train["en"]`                                                | Stores the **English sentences** from the `en` column into the variable `english_sentences`.                                                         |
| `tamil_sentences = train["ta"]`                                                  | Stores the **Tamil sentences** from the `ta` column into the variable `tamil_sentences`.                                                             |
| `english_sentences = english_sentences.head(1000)`                               | Selects only the **first 1000 English sentences** for training or testing.                                                                           |
| `tamil_sentences = tamil_sentences.head(1000)`                                   | Selects only the **first 1000 Tamil sentences** for training or testing.                                                                             |


====

| **Step** | **Operation**             | **Purpose**                                                      |
| -------- | ------------------------- | ---------------------------------------------------------------- |
| **1**    | Import Libraries          | Load Pandas, NumPy, TensorFlow, and Keras.                       |
| **2**    | Read Dataset              | Load the English–Tamil translation dataset.                      |
| **3**    | Remove Unwanted Column    | Delete the `Unnamed: 0` index column.                            |
| **4**    | Extract English Sentences | Store the `en` column in a variable.                             |
| **5**    | Extract Tamil Sentences   | Store the `ta` column in a variable.                             |
| **6**    | Select First 1000 Records | Reduce the dataset size for faster training and experimentation. |

"""

#Function to add SOS and EOS to the statement
from tensorflow import keras
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.models import Sequential

train=pd.read_csv("engtamilTrain.csv", engine='python', on_bad_lines='warn')
train=train.drop(["Unnamed: 0"],axis=1)
english_sentences=train["en"]
tamil_sentence=train['ta']
english_sentences=english_sentences.head(1000)
tamil_sentences=tamil_sentence.head(1000)

def addSosEos(seriesSentence):
    # Define the <SOS> and <EOS> tokens
    sos_token = "<SOS>"
    eos_token = "<EOS>"

    # Add <SOS> and <EOS> tokens to each statement
    statements_with_tokens = [f"{sos_token} {statement} {eos_token}" for statement in seriesSentence]

    english_sent=[]
    # Print the statements with tokens
    for statement in statements_with_tokens:
        english_sent.append(statement)
        print(statement)
    return english_sent

"""| **Code**                                                                                            | **Description**                                                                                                                           |
| --------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------- |
| `from tensorflow import keras`                                                                      | Imports the **Keras** API from TensorFlow to build deep learning models.                                                                  |
| `from tensorflow.keras.layers import Embedding, LSTM, Dense`                                        | Imports the **Embedding**, **LSTM**, and **Dense** layers used in the Seq2Seq model.                                                      |
| `from tensorflow.keras.models import Sequential`                                                    | Imports the **Sequential** model to build the neural network layer by layer.                                                              |
| `train = pd.read_csv("engtamilTrain.csv", engine='python', on_bad_lines='warn')`                    | Reads the English–Tamil dataset from the CSV file. If any row has formatting issues, it displays a warning instead of stopping execution. |
| `train = train.drop(["Unnamed: 0"], axis=1)`                                                        | Removes the unnecessary **Unnamed: 0** column from the dataset.                                                                           |
| `english_sentences = train["en"]`                                                                   | Extracts the English sentences from the **en** column.                                                                                    |
| `tamil_sentence = train["ta"]`                                                                      | Extracts the Tamil sentences from the **ta** column.                                                                                      |
| `english_sentences = english_sentences.head(1000)`                                                  | Selects only the first **1000 English sentences** for training.                                                                           |
| `tamil_sentences = tamil_sentence.head(1000)`                                                       | Selects only the first **1000 Tamil sentences** for training.                                                                             |
| `def addSosEos(seriesSentence):`                                                                    | Defines a function to add **Start of Sentence (SOS)** and **End of Sentence (EOS)** tokens to every sentence.                             |
| `sos_token = "<SOS>"`                                                                               | Defines the **Start of Sentence** token.                                                                                                  |
| `eos_token = "<EOS>"`                                                                               | Defines the **End of Sentence** token.                                                                                                    |
| `statements_with_tokens = [f"{sos_token} {statement} {eos_token}" for statement in seriesSentence]` | Adds **<SOS>** at the beginning and **<EOS>** at the end of every sentence using list comprehension.                                      |
| `english_sent = []`                                                                                 | Creates an empty list to store the modified sentences.                                                                                    |
| `for statement in statements_with_tokens:`                                                          | Iterates through each modified sentence.                                                                                                  |
| `english_sent.append(statement)`                                                                    | Stores each modified sentence into the list.                                                                                              |
| `print(statement)`                                                                                  | Prints every sentence with **SOS** and **EOS** tokens.                                                                                    |
| `return english_sent`                                                                               | Returns the list containing all modified sentences.                                                                                       |


====

| **Step** | **Operation**                 | **Purpose**                                               |
| -------- | ----------------------------- | --------------------------------------------------------- |
| **1**    | Read Dataset                  | Load English–Tamil translation dataset.                   |
| **2**    | Remove Extra Column           | Delete the unnecessary `Unnamed: 0` column.               |
| **3**    | Extract English Sentences     | Store English sentences from the `en` column.             |
| **4**    | Extract Tamil Sentences       | Store Tamil sentences from the `ta` column.               |
| **5**    | Select First 1000 Records     | Reduce the dataset size for faster training.              |
| **6**    | Define `addSosEos()` Function | Create a function to add **SOS** and **EOS** tokens.      |
| **7**    | Add `<SOS>`                   | Marks the beginning of each sentence.                     |
| **8**    | Add `<EOS>`                   | Marks the end of each sentence.                           |
| **9**    | Store Modified Sentences      | Save the updated sentences in a list.                     |
| **10**   | Print Sentences               | Display each sentence with the added tokens.              |
| **11**   | Return List                   | Return the modified sentence list for further processing. |


==========


"""

english_sent_SE=addSosEos(english_sentences)
tamil_sent_SE=addSosEos(tamil_sentences)

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Embedding, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Tokenize the English and Tamil sentences
english_tokenizer = Tokenizer(filters="")
english_tokenizer.fit_on_texts(english_sent_SE)
english_vocab_size = len(english_tokenizer.word_index) + 1
english_sequences = english_tokenizer.texts_to_sequences(english_sent_SE)

tamil_tokenizer = Tokenizer(filters="")
tamil_tokenizer.fit_on_texts(tamil_sent_SE)
tamil_vocab_size = len(tamil_tokenizer.word_index) + 1
tamil_sequences = tamil_tokenizer.texts_to_sequences(tamil_sent_SE)

max_input_seq_length=20
max_output_seq_length=20

# Pad sequences to a fixed length
input_sequences = pad_sequences(english_sequences, maxlen=max_input_seq_length, padding='post')
output_sequences = pad_sequences(tamil_sequences, maxlen=max_output_seq_length, padding='post')

# Prepare the decoder input and output sequences for teacher forcing
decoder_input_sequences = np.zeros_like(output_sequences)
decoder_input_sequences[:, 1:] = output_sequences[:, :-1]
decoder_input_sequences[:, 0] = tamil_tokenizer.word_index['<sos>']

decoder_output_sequences = np.eye(tamil_vocab_size)[output_sequences]

!pip install gensim
from gensim.models import Word2Vec

eng_model = Word2Vec.load('engmodel.bin')
tam_model = Word2Vec.load('tammodel.bin')

def create_embedding_matrix(word2vec_model, tokenizer, vocab_size):
    embedding_matrix = np.zeros((vocab_size, word2vec_model.vector_size))
    for word, i in tokenizer.word_index.items():
        try:
            embedding_vector = word2vec_model.wv[word]
            embedding_matrix[i] = embedding_vector
        except KeyError:
            pass  # Words not found in the embedding index will be all zeros
    return embedding_matrix

eng_embedding_matrix = create_embedding_matrix(eng_model, english_tokenizer, english_vocab_size)
tam_embedding_matrix = create_embedding_matrix(tam_model, tamil_tokenizer, tamil_vocab_size)

eng_embedding_matrix.shape

tam_embedding_matrix.shape

def create_seq2seq_model(input_vocab_size, output_vocab_size, input_seq_length, output_seq_length, hidden_units, eng_embedding_matrix, tam_embedding_matrix):
    # Encoder
    encoder_inputs = Input(shape=(input_seq_length,))
    encoder_embedding = Embedding(input_vocab_size, hidden_units, weights=[eng_embedding_matrix], trainable=False)(encoder_inputs)
    encoder_lstm, encoder_state_h, encoder_state_c = LSTM(hidden_units, return_state=True)(encoder_embedding)

    # Decoder
    decoder_inputs = Input(shape=(output_seq_length,))
    decoder_embedding = Embedding(output_vocab_size, hidden_units, weights=[tam_embedding_matrix], trainable=False)(decoder_inputs)
    decoder_lstm = LSTM(hidden_units, return_sequences=True, return_state=True)
    decoder_outputs, _, _ = decoder_lstm(decoder_embedding, initial_state=[encoder_state_h, encoder_state_c])
    decoder_dense = Dense(output_vocab_size, activation='softmax')
    decoder_outputs = decoder_dense(decoder_outputs)

    model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
    return model

# Convert target_sequences to one-hot encoded format
target_sequences = tf.keras.utils.to_categorical(output_sequences, num_classes=tamil_vocab_size)

model = create_seq2seq_model(english_vocab_size, tamil_vocab_size, max_input_seq_length, max_output_seq_length, 100, eng_embedding_matrix, tam_embedding_matrix)

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Fit the model to the data
batch_size = 32
epochs = 500
model.fit([input_sequences, output_sequences], decoder_output_sequences, batch_size=batch_size, epochs=epochs, validation_split=0.2)

# Preprocessing the input
input_sentence = "<sos>Finally, the columnist fails to tell us who among the political leaders of the bourgeoisie, past and present, he counts among the paragons of morality<eos>"

# Convert the input sentence to sequence
input_sequence = english_tokenizer.texts_to_sequences([input_sentence])

# Pad the statement to the maximum input sequence length
input_sequence = pad_sequences(input_sequence, maxlen=max_input_seq_length, padding='post')

# Generate predictions
predictions = model.predict([input_sequence, np.zeros((1, max_output_seq_length))])

# Convert predictions to tokens
predicted_tokens = np.argmax(predictions, axis=-1)[0]

# Create index to word mapping for Tamil vocabulary
tamil_index_word = {i: w for w, i in tamil_tokenizer.word_index.items()}


# Convert tokens to text
decoded_sentence = []
for token in predicted_tokens:
    if token == 0:  # Assuming 0 is the padding token
        continue
    word = tamil_index_word.get(token)
    if word == '<eos>':
        break
    if word is not None:
        decoded_sentence.append(word)
    else:
        decoded_sentence.append('<unk>')

# Join the words to form the decoded statement
decoded_statement = ' '.join(decoded_sentence)

# Print the decoded statement
print(decoded_statement)

predictions

predicted_tokens

input_sequence

input_sequence